"""Generate a high-level Excalidraw diagram for Layer 6."""

from pathlib import Path

from _lib import BLUE, GREEN, GRAY, ORANGE, PALE_BLUE, RED, VIOLET, YELLOW, Diagram

OUT = Path(__file__).with_name("06-editorial-layer.excalidraw")


def build() -> Diagram:
    d = Diagram()
    d.header(
        "Layer 6 — Human Editorial Decision",
        "NewsAuth · Thesis B · COMP4092     The journalist records the newsroom outcome. No model runs. The system recommendation is visible and is never auto-committed.",
    )
    d.pipeline_chips(60, 132, active=6)

    d.box(
        "from-l5",
        420,
        200,
        1100,
        96,
        "From Layer 5 — publication risk and a recommended label",
        "Plus every earlier signal: claims, retrieved articles, corroboration states, unknowns. All of it is decision support. None of it is the verdict.",
        fill=PALE_BLUE,
        title_size=18,
        body_size=15,
    )

    d.box(
        "halt",
        420,
        324,
        1100,
        56,
        "The pipeline stops here. The system will not auto-commit.",
        fill=YELLOW,
        title_size=16,
    )

    d.box(
        "sees",
        60,
        416,
        900,
        248,
        "What the journalist sees (read-only)",
        "The Layer 5 recommended label is shown as a suggestion, already marked “not a verdict”.\n"
        "\n"
        "They can still inspect publication risk, corroboration, disagreements, and empty tools.\n"
        "\n"
        "They may pick a different label from the recommendation. That is the point.",
        fill=PALE_BLUE,
        title_size=18,
        body_size=15,
    )

    d.box(
        "refuses",
        1020,
        416,
        860,
        248,
        "What the system refuses to do",
        "No LLM is called. Engine: dashboard (no model).\n"
        "\n"
        "Proceed is blocked — “submit an editorial decision to continue”.\n"
        "Re-run is blocked — “editorial decision cannot be generated by the system”.\n"
        "\n"
        "The pipeline cannot skip this human.",
        fill=RED,
        title_size=18,
        body_size=15,
    )

    d.text("labels-h", 60, 692, "The journalist chooses one newsroom label", size=16, color="#495057")
    labels = [
        ("d-ver", "verified", "Treat as checked\nfor publication"),
        ("d-mis", "misleading", "Substance may hold;\nframing does not"),
        ("d-man", "manipulated", "Content looks\naltered or staged"),
        ("d-uns", "unsupported", "Not enough to\nstand the claim up"),
        ("d-unv", "unverifiable", "Cannot be checked\nwith what we have"),
        ("d-inv", "needs investigation", "Not ready — keep\nworking the story"),
    ]
    x = 60
    for key, title, body in labels:
        d.box(key, x, 720, 292, 110, title, body, fill=VIOLET, title_size=16, body_size=13)
        x += 308

    d.box(
        "confirm",
        60,
        868,
        900,
        168,
        "Optional notes, then Confirm",
        "Notes are stored with the label. Confirm is disabled until a label is chosen.\n"
        "On confirm the dashboard POSTs the decision. That is the only way this layer completes.",
        fill=ORANGE,
        title_size=18,
        body_size=15,
    )
    d.box(
        "record",
        996,
        868,
        884,
        168,
        "What gets written",
        "human_decision: the chosen label, notes, and UTC timestamp.\n"
        "Trace: “Recorded {label}; not an authenticity verdict.”\n"
        "Layer 7 then starts immediately — there is no second Proceed.",
        fill=GREEN,
        title_size=18,
        body_size=15,
    )

    d.text("out-label", 60, 1068, "What this layer produces", size=16, color="#495057")
    cards = [
        ("out-label-card", "Editorial label", "One of the six newsroom\noutcomes, chosen by a human"),
        ("out-notes", "Editorial notes", "Free-text rationale,\nor empty"),
        ("out-when", "Decided at", "UTC timestamp on\nthe run envelope"),
        ("out-rec", "Recommendation kept", "Layer 5’s suggestion stays\nvisible; it is not overwritten"),
        ("out-no-model", "No engine used", "dashboard (no model)\nis recorded on purpose"),
        ("out-lock", "Decision is locked", "Once confirmed, this layer\ncannot be re-generated"),
    ]
    x = 60
    for key, title, body in cards:
        d.box(key, x, 1096, 292, 120, title, body, fill=GRAY if key == "out-lock" else PALE_BLUE, title_size=15, body_size=13)
        x += 308

    d.box(
        "gate",
        60,
        1256,
        900,
        120,
        "Confirm is the only gate",
        "There is no Proceed / Re-run / Ask on this card.\n"
        "Confirm records the human, then Layer 7 writes the verification record.",
        fill=ORANGE,
        title_size=17,
        body_size=15,
    )
    d.box(
        "next",
        996,
        1256,
        360,
        120,
        "Next: Layer 7",
        "Output and\nDocumentation",
        fill=BLUE,
        title_size=17,
        body_size=15,
    )
    d.box(
        "not",
        1388,
        1256,
        492,
        120,
        "This layer does not",
        "Invent a verdict, auto-select the recommended label, or let the pipeline finish without a journalist.",
        fill=RED,
        title_size=17,
        body_size=15,
    )

    d.arrow("a-in-halt", "from-l5", "halt")
    d.arrow("a-halt-sees", "halt", "sees")
    d.arrow("a-halt-ref", "halt", "refuses")
    d.arrow("a-sees-ver", "sees", "d-ver")
    d.arrow("a-ver-con", "d-ver", "confirm", drop="src")
    d.arrow("a-con-rec", "confirm", "record", src_side="right", dst_side="left")
    d.arrow("a-rec-out", "record", "out-no-model", drop="src")
    d.arrow("a-out-gate", "out-label-card", "gate", drop="src")
    d.arrow("a-gate-next", "gate", "next", src_side="right", dst_side="left")

    return d


def main() -> None:
    build().write(OUT)


if __name__ == "__main__":
    main()
